# Generated by Django 3.2.3 on 2021-05-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210524_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(choices=[('JS', 'JavaScript'), ('PY', 'Python'), ('REACT', 'React')], default='JS', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
