# Generated by Django 3.2.3 on 2021-05-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20210525_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
