# Generated by Django 3.2.3 on 2021-05-25 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_profile_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
