# Generated by Django 3.2.3 on 2021-05-27 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['hour']},
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(choices=[('JS', 'JavaScript'), ('PY', 'Python'), ('REACT', 'React'), ('DJANGO', 'Django'), ('TYPESCRIPT', 'Typescript')], default='JS', max_length=100),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='hour',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
