# Generated by Django 3.2.3 on 2021-05-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['post_date']},
        ),
    ]
