# Generated by Django 3.2.3 on 2021-05-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['post_date']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.CharField(choices=[('JS', 'JavaScript'), ('PY', 'Python'), ('REACT', 'React'), ('DJANGO', 'Django'), ('TYPESCRIPT', 'Typescript'), ('EXPRESS', 'Express.js'), ('NODE', 'Node.js'), ('JAVA', 'Java'), ('C++', 'C++'), ('C#', 'C#'), ('PHP', 'PHP'), ('FLASK', 'Flask'), ('RUBY', 'Ruby'), ('RUBYONRAILS', 'Ruby On Rails'), ('SQL', 'SQL'), ('COBOL', 'Cobol'), ('WORDPRESS', 'WordPress'), ('C', 'C'), ('OBJECTIVEC', 'Objective C'), ('SWIFT', 'Swift'), ('SCALA', 'Scala'), ('GO', 'GO'), ('ELM', 'Elm'), ('MUMPS', 'MUMPS'), ('RUST', 'Rust'), ('HTML', 'HTML'), ('CSS', 'CSS')], default='JS', max_length=100),
        ),
    ]
