# Generated by Django 3.2.3 on 2021-06-02 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_review_options'),
        ('main_app', '0011_auto_20210528_1517'),
    ]

    operations = [
    ]
