# Generated by Django 3.2.3 on 2021-06-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_profile_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='place_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
